name: Auto EDA Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-eda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run EDA Script
        run: python scripts/run_eda.py

      # Debug: Ensure the report directory exists
      - name: Verify EDA Report Directory
        run: |
          echo "Checking if eda_reports directory exists..."
          ls -R eda_reports/ || echo "No EDA reports found!"

      # Upload EDA Report as an Artifact
      - name: Upload EDA Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: eda-report
          path: eda_reports/**/*.html  # Upload only HTML reports
          if-no-files-found: error  # Fail if reports are missing
