name: Feature Engineering Pipeline

on:
  push:
    branches:
      - main  # Runs feature engineering on any push to main

jobs:
  run-feature-engineering:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download EDA Report (Optional)
        continue-on-error: true  # Allow pipeline to continue if EDA report is missing
        uses: actions/download-artifact@v4
        with:
          name: eda-report
          path: eda_reports/

      - name: Run Feature Engineering
        run: python scripts/feature_engineering.py

      - name: Upload Processed Data & Model as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: processed-data-and-model
          path: |
            models/
            processed_data/
          if-no-files-found: error  # Fail if no files are found
