name: MLflow Model Tracking & Drift Detection

on:
  push:
    branches:
      - main  # Runs MLflow tracking on any push to main

jobs:
  mlflow-tracking:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # ✅ Now supports Python 3.9+

      - name: Cache Python Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run MLflow Model Training & Drift Detection
        run: python scripts/mlflow_tracking.py

      - name: Debug MLflow Logs
        run: |
          echo "Checking if MLflow logs exist..."
          ls -R mlruns/ || echo "❌ No MLflow logs found!"

      - name: Upload MLflow Logs & Model Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-logs
          path: mlruns/
          if-no-files-found: error  # Fail if logs are missing
